// Foundational "larder" recipes, transcribed from the Core Basics chapter.
// Convention: a line in `ingredients` or `method` that starts with "§ " is a
// sub-heading (e.g. "§ To clarify", "§ Day 1") rather than a normal line.

export type CoreCategoryId =
  | "stocks-and-sauces"
  | "powders"
  | "butters"
  | "brines"
  | "oils-and-gels"
  | "mousse"
  | "pastry"
  | "bakery";

export type CoreCategory = {
  id: CoreCategoryId;
  label: string;
  blurb: string;
};

export type CoreRecipe = {
  slug: string;
  name: string;
  category: CoreCategoryId;
  ingredients: string[];
  method: string[];
};

export const coreIntro =
  "These recipes are the foundation of the cuisine. Without attending to the fine details that make these basics what they are, it is impossible to build layers of flavour and complexity in what you cook. They are as useful in the home kitchen as the professional one — the essentials that, once mastered, give you the confidence of a well-stocked and flavourful larder.";

export const coreCategories: CoreCategory[] = [
  { id: "stocks-and-sauces", label: "Stocks & sauces", blurb: "Stocks, broths, nages, consommés and the reduced sauces built from them." },
  { id: "powders", label: "Powders", blurb: "Dehydrated vegetables, cheeses and aromatics blended to fine powders." },
  { id: "butters", label: "Butters, purées & basics", blurb: "Compound butters, purées, confits and other building blocks." },
  { id: "brines", label: "Brines & pickles", blurb: "Herb brines and pickling liquors." },
  { id: "oils-and-gels", label: "Oils & gels", blurb: "Herb oils, set gels and emulsions." },
  { id: "mousse", label: "Mousse", blurb: "Light protein mousses." },
  { id: "pastry", label: "Pastry", blurb: "Purées, cordials, syrups and sugar work for the sweet side." },
  { id: "bakery", label: "Bakery", blurb: "Sourdough starters built over days." },
];

export const coreRecipes: CoreRecipe[] = [
  // ————————————————————————————————— POWDERS —————————————————————————————————
  {
    slug: "asparagus-powder",
    name: "Asparagus powder",
    category: "powders",
    ingredients: ["250 g green asparagus peelings"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the peelings onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "black-olive-powder",
    name: "Black olive powder",
    category: "powders",
    ingredients: ["250 g black olives, pitted"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the olives onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "buckwheat-powder",
    name: "Buckwheat powder",
    category: "powders",
    ingredients: ["250 g buckwheat kernels"],
    method: [
      "Toast the buckwheat kernels in a frying pan, or on a tray in the oven at 180°C / 350°F (no fan), until lightly toasted.",
      "Leave to cool, then place in a blender and blend to a powder. Pass through a chinois and reserve in an airtight container.",
    ],
  },
  {
    slug: "yeast-crumble",
    name: "Yeast crumble",
    category: "powders",
    ingredients: ["250 g fresh yeast"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Crumble the yeast, spread evenly onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, rub the yeast between your fingers into a fine crumble. Reserve in an airtight container.",
    ],
  },
  {
    slug: "celeriac-top-powder",
    name: "Celeriac top powder",
    category: "powders",
    ingredients: ["250 g celeriac leaves"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the leaves onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "cep-powder",
    name: "Cep powder",
    category: "powders",
    ingredients: ["50 g ceps"],
    method: [
      "Preheat a dehydrator to 65°C / 150°F. Clean the ceps with a brush and thinly slice.",
      "Evenly spread the ceps onto a dehydrator tray and allow to fully dry for 24 hours. Once dried, blend to a powder and reserve in an airtight container.",
    ],
  },
  {
    slug: "parmesan-powder",
    name: "Parmesan powder",
    category: "powders",
    ingredients: ["250 g Parmesan, grated"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the Parmesan onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "pea-powder",
    name: "Pea powder",
    category: "powders",
    ingredients: ["250 g fresh peas"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the peas onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "pumpkin-powder",
    name: "Pumpkin powder",
    category: "powders",
    ingredients: ["250 g peeled pumpkin flesh, sliced"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Evenly spread the pumpkin slices onto a dehydrator tray and allow to fully dry for 8 hours.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },
  {
    slug: "shiitake-powder",
    name: "Shiitake powder",
    category: "powders",
    ingredients: ["250 g shiitake mushrooms"],
    method: [
      "Preheat a dehydrator to 65°C / 150°F. Clean the shiitakes with a brush, then thinly slice.",
      "Evenly spread the shiitakes onto a dehydrator tray and allow to fully dry for 24 hours. Once dried, blend to a powder and reserve in an airtight container.",
    ],
  },
  {
    slug: "basil-powder",
    name: "Basil powder",
    category: "powders",
    ingredients: ["250 g basil leaves", "4 kg water", "salt, to taste"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Bring a large saucepan of salted water to the boil and blanch the leaves. Place in an ice bath and pat dry with paper towels.",
      "Evenly spread the leaves onto a dehydrator tray and allow to fully dry for 6 hours, or until crispy. Once dried, blend to a powder, then season to taste. Reserve in an airtight container.",
    ],
  },
  {
    slug: "garlic-powder",
    name: "Garlic powder",
    category: "powders",
    ingredients: ["1 kg whole milk", "250 g peeled garlic cloves, thinly sliced", "salt, to taste"],
    method: [
      "Preheat a dehydrator to 65°C / 150°F. Bring the milk to the boil in a medium saucepan and season to taste. Add the garlic and blanch until tender. Drain and pat dry with paper towels.",
      "Evenly spread the garlic onto a dehydrator tray and dry for 6 hours, or until crispy. Blend the dried garlic to a powder and season to taste. Reserve in an airtight container.",
    ],
  },
  {
    slug: "onion-powder",
    name: "Onion powder",
    category: "powders",
    ingredients: ["1 kg whole milk", "250 g peeled white onions, thinly sliced", "salt, to taste"],
    method: [
      "Preheat a dehydrator to 65°C / 150°F. Bring the milk to the boil in a medium saucepan and season to taste. Add the onions and blanch until tender. Drain and pat dry with paper towels.",
      "Evenly spread the onions onto a dehydrator tray and dry for 6 hours, or until crispy. Blend the dried onions to a powder and season to taste. Reserve in an airtight container.",
    ],
  },
  {
    slug: "tomato-powder",
    name: "Tomato powder",
    category: "powders",
    ingredients: ["250 g red tomato skins", "salt, to taste", "caster sugar, to taste"],
    method: [
      "Preheat a dehydrator to 75°C / 165°F. Season the tomato skins with salt and sugar. Evenly spread onto a dehydrator tray and dry for 6 hours, or until crispy.",
      "Once dried, place in a blender and blend to a powder. Reserve in an airtight container.",
    ],
  },

  // ———————————————————————————— STOCKS & SAUCES ————————————————————————————
  {
    slug: "mushroom-juice",
    name: "Mushroom juice",
    category: "stocks-and-sauces",
    ingredients: ["600 g chestnut mushrooms", "200 g water", "6 g salt"],
    method: [
      "Blend the mushrooms and water in a blender, then transfer to a large bowl and add the salt.",
      "Prepare a perforated tray lined with a double layer of muslin cloth set over a large gastronorm tray. Spread the mixture onto the muslin, then place another tray on top to weight it down.",
      "Leave in the fridge for 24 hours, until all the juice has drained.",
    ],
  },
  {
    slug: "dashi-stock",
    name: "Dashi stock",
    category: "stocks-and-sauces",
    ingredients: [
      "1 kg mineral water",
      "12 g dried shiitake mushrooms",
      "15 g large dried kombu",
      "25 g bonito flakes",
      "white soy sauce, to taste",
      "ponzu, to taste",
      "salt, to taste",
    ],
    method: [
      "Combine the water, mushrooms and kombu in a large saucepan over a medium heat. Cover and heat to 60°C / 140°F, then remove from the heat and infuse for 1 hour.",
      "Line a chinois with muslin. Discard the kombu and heat the remaining broth to 80°C / 175°F. Add the bonito flakes, stir for 15 seconds, then immediately strain through the lined chinois.",
      "Season the broth to taste with soy sauce, ponzu and salt.",
    ],
  },
  {
    slug: "vegetable-nage",
    name: "Vegetable nage",
    category: "stocks-and-sauces",
    ingredients: [
      "200 g carrots, cut into 4-cm (1½-inch) dice",
      "200 g onions, cut into 4-cm (1½-inch) dice",
      "200 g celery, cut into 4-cm (1½-inch) dice",
      "300 g leeks, cut into 4-cm (1½-inch) dice",
      "cold water, to cover",
      "1 g black peppercorns",
      "3 g fennel seeds",
      "2 g coriander seeds",
      "1 bay leaf",
      "200 g white wine",
      "1 slice of lemon, 2 cm (¾ inch) thick",
      "10 g sprigs parsley",
      "10 g sprigs chervil",
    ],
    method: [
      "Put all the vegetables into a large saucepan over a medium heat. Cover with cold water and bring to the boil, then add the aromatics and white wine.",
      "Remove from the heat, add the lemon slice and fine herbs, and leave to infuse in the fridge for 24 hours. Pass through a chinois into a container and reserve until required.",
    ],
  },
  {
    slug: "crab-consomme",
    name: "Crab consommé",
    category: "stocks-and-sauces",
    ingredients: [
      "2.5 kg cock crab shells (14 medium crabs)",
      "85 g brandy",
      "250 g white wine",
      "100 g grapeseed oil",
      "60 g butter",
      "625 g carrots, thinly sliced",
      "400 g onions, thinly sliced",
      "110 g leeks, thinly sliced",
      "60 g celery, thinly sliced",
      "5 g garlic clove, thinly sliced",
      "40 g lemongrass",
      "½ fennel stalk",
      "5 g fennel seeds",
      "3 g coriander seeds",
      "4 g white peppercorns",
      "1 bay leaf",
      "1 g star anise",
      "5 sprigs thyme",
      "2 kg cold water",
      "2 kg chicken stock",
      "§ To finish the consommé",
      "10 g chervil",
      "5 g parsley",
      "10 g lemongrass",
      "grated zest of 1 lemon",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (no fan). Roast the crab shells in a tray for about 30 minutes until golden. Place into a stand mixer and mix to crush the shells. Drain in a colander and reserve the juices.",
      "Flambé the brandy and wine in two separate pans over a medium heat. Once the alcohol has burned off, add the brandy to the wine and reduce by half, then set aside.",
      "Put the grapeseed oil, butter, carrots, onions, leeks, celery and garlic into a large pressure cooker and cook over a medium heat until softened and lightly caramelized. Add the roasted crab shells, crab juices, aromatics and flambéed alcohol, then add the water and chicken stock and bring to the boil, continuously skimming. Secure the lid and cook on full pressure for 2 hours.",
      "Once depressurized, pass the stock through a fine chinois, then through a double layer of muslin into a deep gastronorm tray and freeze, to start the ice-filtration process. Place the frozen block into muslin on a perforated tray with a tray underneath and defrost in the fridge for 1–2 days (clarification is ready once the liquid has melted and only the impurities remain).",
      "Pour the clarified consommé into a large saucepan over a medium heat and reduce by half, skimming. To finish, add the herbs, lemongrass and lemon zest, infuse for 15 minutes, then cool over an ice bath.",
    ],
  },
  {
    slug: "lobster-consomme",
    name: "Lobster consommé",
    category: "stocks-and-sauces",
    ingredients: [
      "300 g lobster shells",
      "150 g olive oil",
      "50 g butter",
      "25 g carrots, thinly sliced",
      "16 g onions, thinly sliced",
      "20 g leeks, thinly sliced",
      "10 g celery stick, thinly sliced",
      "1 garlic clove, thinly sliced",
      "250 g white wine",
      "100 g brandy",
      "1 kg fish stock",
      "1 kg lobster stock",
    ],
    method: [
      "Place the lobster shells in a stand mixer fitted with the paddle and mix to crush. Drain in a colander and reserve the juices.",
      "Preheat a roasting pan over a medium heat with 50 g of the olive oil. Once hot, add the shells and roast until lightly golden. Drain off the fat.",
      "Heat a medium saucepan over a medium heat, add the remaining olive oil, the butter and the vegetables and garlic, and cook until soft and lightly browned. Add the roasted shells, reserved juice, white wine and brandy and reduce to a syrup over a high heat. Add both stocks and bring to the boil, skimming, then reduce and simmer gently for 1 hour.",
      "Pass through a fine chinois, then a double layer of muslin, into a deep gastronorm tray and freeze to start the ice-filtration process. Place the frozen block into muslin on a perforated tray with a tray underneath and defrost in the fridge for 1–2 days.",
      "Pour the clarified consommé into a large saucepan over a medium heat and reduce by half, skimming. Allow to cool over an ice bath.",
    ],
  },
  {
    slug: "lobster-stock",
    name: "Lobster stock",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "400 g crushed lobster shells",
      "100 g carrots, diced",
      "100 g onions, diced",
      "100 g celery, diced",
      "20 g tomato purée (paste)",
      "cold water, to cover",
      "4 sprigs thyme",
      "2 garlic cloves",
    ],
    method: [
      "Heat the oil in a medium saucepan over a high heat, then add the crushed lobster shells and cook until lightly roasted. Add the vegetables and tomato purée, cover with cold water and add the thyme and garlic.",
      "Bring to the boil, then reduce the heat and simmer gently for 2 hours, skimming off any impurities. Pass through a chinois into a container and place in the fridge.",
    ],
  },
  {
    slug: "mussel-broth",
    name: "Mussel broth",
    category: "stocks-and-sauces",
    ingredients: [
      "1.2 kg cleaned, debearded mussels",
      "25 g olive oil",
      "2.5 g garlic cloves, chopped",
      "180 g shallots, chopped",
      "120 g celery, chopped",
      "120 g leeks, chopped",
      "300 g carrots, chopped",
      "24 g thyme",
      "2 g bay leaves",
      "1.2 kg white wine",
      "3 kg fish stock",
      "salt, to taste",
      "§ To clarify",
      "222 g egg whites",
      "120 g mussel meat",
    ],
    method: [
      "Place the mussels onto a perforated tray with a tray underneath and steam at 100°C / 210°F until they open. Drain the juices into a container and plunge the mussels into an ice bath. Pick the meat and reserve.",
      "Heat the olive oil in a large saucepan over a medium heat, add the garlic and shallots, lightly season and cook for 1 minute, then add the remaining vegetables and herbs. Cook until soft without colour, then pour in the wine and reduce until only a few spoonfuls remain. Add the fish stock and mussel juice and reduce by two thirds, skimming. Strain through a chinois into a container over an ice bath.",
      "To clarify, blend 72 g of the egg whites with the mussel meat for 3 minutes, then transfer to a bowl. Whisk the remaining 150 g egg whites to soft peaks and fold into the mussel mixture. Combine with the reduced stock in a large saucepan over a medium heat, whisk, then bring to a gentle simmer, whisking occasionally so the whites don't stick. Simmer for 40 minutes, or until clear. Siphon off the stock and pass through muslin into a container. Chill over an ice bath.",
    ],
  },
  {
    slug: "fish-stock",
    name: "Fish stock",
    category: "stocks-and-sauces",
    ingredients: [
      "3 kg white fish bones",
      "5 kg water",
      "500 g white wine",
      "150 g white onions, sliced",
      "150 g fennel, sliced",
      "150 g celery, sliced",
      "150 g leeks, sliced",
    ],
    method: [
      "Rinse the fish bones until the water runs clear, then put into a large saucepan with the water and wine and bring to the boil.",
      "Once boiling, remove from the heat, skim off the impurities that rise to the surface and add the vegetables. Allow to cool for 30 minutes. Strain through a chinois, then through muslin.",
    ],
  },
  {
    slug: "chicken-stock",
    name: "Chicken stock",
    category: "stocks-and-sauces",
    ingredients: [
      "2 kg chicken wings",
      "cold water, to cover",
      "150 g onions, diced",
      "125 g carrots, diced",
      "125 g celery, diced",
      "125 g leeks, diced",
      "2 g garlic clove",
      "8 sprigs thyme",
      "1 bay leaf",
      "2 g black peppercorns",
    ],
    method: [
      "Place the chicken wings in a large pot, cover with cold water and bring to the boil, then remove the wings and rinse under cold running water to remove impurities.",
      "Transfer the wings to a large saucepan, cover with cold water and bring to a simmer over a high heat, skimming. Add the vegetables, garlic, herbs and peppercorns and bring back to the boil, then reduce the heat and simmer for 8 hours.",
      "Pass through muslin, then a chinois, into a container. Let it cool over an ice bath.",
    ],
  },
  {
    slug: "beef-stock",
    name: "Beef stock",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "2 kg beef bones",
      "2 kg beef chuck, diced",
      "100 g white onions, diced",
      "100 g leeks, diced",
      "100 g carrots, diced",
      "30 g garlic head, cut in half",
      "10 sprigs thyme",
      "1 bay leaf",
      "1 g black peppercorns",
      "5 kg water",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil. Once hot, add the beef bones and roast until golden.",
      "Heat a little oil in a large saucepan over a medium heat, add the diced beef and cook until browned all over. Remove the beef and drain off the excess fat. Add the vegetables and garlic to the same pan, lightly season, and cook until golden brown, then add the herbs and peppercorns. Return the beef and add the roasted bones, scraping the bottom with a spatula so nothing sticks.",
      "Add the water, bring to the boil, then reduce the heat and simmer gently for 8 hours, skimming. Strain through a fine chinois, then muslin, into a clean saucepan. Reduce the stock by half. Remove from the heat and allow to cool.",
    ],
  },
  {
    slug: "veal-stock",
    name: "Veal stock",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "4 kg veal bones",
      "2 onions, diced",
      "2 leeks, diced",
      "4 celery sticks, diced",
      "2 large carrots, diced",
      "1 garlic head, cut in half",
      "100 g tomato purée (paste)",
      "10 sprigs thyme",
      "2 bay leaves",
      "20 black peppercorns",
      "6 kg water",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil. Once hot, add the veal bones and roast until golden brown.",
      "Heat a little oil in a large stock pot over a medium heat and cook all the vegetables and garlic, then lightly season. Once browned, add the tomato purée, herbs and peppercorns. Add the roasted bones, cover with the water and bring to the boil, skimming off any impurities, for 24 hours.",
      "Strain through a fine chinois, then muslin, into a clean pan and reduce by half. Remove from the heat and allow to cool over ice.",
    ],
  },
  {
    slug: "lamb-stock",
    name: "Lamb stock",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "2 kg lamb bones",
      "2 kg lamb rump, diced",
      "100 g white onions, diced",
      "100 g leeks, diced",
      "100 g carrots, diced",
      "25 g garlic head, cut in half",
      "2 g thyme",
      "2 g rosemary",
      "1 bay leaf",
      "1 g black peppercorns",
      "4 kg water",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F. Heat an oven tray with a dash of grapeseed oil. Once hot, add the lamb bones and roast until golden.",
      "Heat a little oil in a large saucepan over a medium heat, add the diced lamb and cook until browned all over. Remove and drain off the excess fat. Add the vegetables and garlic and cook until browned, then add the herbs and peppercorns. Return the lamb and add the roasted bones, scraping the bottom so nothing sticks.",
      "Add the water, bring to the boil, then reduce the heat and simmer gently for 8 hours. Strain through a fine chinois, then muslin, into a clean saucepan. Reduce by half. Remove from the heat and allow to cool.",
    ],
  },
  {
    slug: "chicken-consomme",
    name: "Chicken consommé",
    category: "stocks-and-sauces",
    ingredients: [
      "150 g grapeseed oil",
      "300 g chicken wings, diced",
      "25 g carrots, thinly sliced",
      "16 g onions, thinly sliced",
      "20 g leeks, thinly sliced",
      "10 g celery, thinly sliced",
      "1 garlic clove, thinly sliced",
      "50 g butter",
      "4 sprigs thyme",
      "1 bay leaf",
      "5 g black peppercorns",
      "2 kg chicken stock",
      "1 whole chicken, quartered",
      "§ To clarify",
      "100 g chicken breast",
      "25 g shallots",
      "25 g leek",
      "25 g celery",
      "100 g egg whites",
    ],
    method: [
      "Heat the oil in a large saucepan over a medium heat, add the chicken wings and cook until golden brown. Drain off any excess fat. Add the vegetables and garlic and cook until lightly brown, then add the butter, herbs and peppercorns. Add the quartered chicken, reduce the heat and simmer for 2 hours, continuously skimming. Pass through a chinois into a clean saucepan and cool to room temperature.",
      "To clarify, blend the chicken breast, shallots, leek and celery in a food processor until minced. Add a good pinch of salt. Whisk the egg whites to soft peaks, then fold into the chicken mixture. Add to the stock and whisk well. Bring to a simmer, gently whisking as it heats so the raft doesn't stick. Once the raft begins to form, stop whisking and leave to cook without boiling.",
      "Make a small hole in the raft and, once the stock is clear, remove from the heat. Using a ladle, carefully pass the consommé through muslin into a container. Chill over ice and reserve until required.",
    ],
  },
  {
    slug: "duck-stock",
    name: "Duck stock",
    category: "stocks-and-sauces",
    ingredients: [
      "25 g grapeseed oil, plus extra for roasting",
      "2.5 kg duck bones",
      "25 g butter",
      "125 g carrots, coarsely chopped",
      "125 g onions, coarsely chopped",
      "125 g celery, coarsely chopped",
      "2 garlic cloves",
      "10 sprigs thyme",
      "5 g white peppercorns",
      "3 kg chicken stock",
      "1 kg veal stock",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil, add the duck bones and cook until browned all over.",
      "Heat the grapeseed oil in a stock pot over a medium heat, add the butter, vegetables and garlic, lightly season, then cook until browned. Add the thyme and peppercorns and cook for another 2 minutes, then add the roasted bones and both stocks.",
      "Bring to the boil, reduce the heat and simmer for 2 hours, continuously skimming. Pass through a fine chinois into a container over ice.",
    ],
  },
  {
    slug: "beef-sauce",
    name: "Beef sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "100 g beef fat",
      "3 kg beef chuck, diced",
      "700 g shallots, sliced",
      "100 g garlic cloves",
      "100 g butter",
      "1 bay leaf",
      "8 sprigs thyme",
      "10 g black peppercorns",
      "50 g Cabernet Sauvignon vinegar",
      "100 g Cognac",
      "750 g red wine",
      "2 kg beef stock",
      "2 kg veal stock",
      "roasted bones (reserved from the stocks above)",
      "salt, to taste",
    ],
    method: [
      "Melt the beef fat in a large pot over a medium heat, add the diced beef, season with salt, and cook until browned. Remove the beef, drain through a sieve and set aside.",
      "Add the shallots and garlic to the pot with the butter, season with salt, and brown, then add the herbs, peppercorns and the beef. Pour in the vinegar and reduce to a glaze, scraping the bottom so the meat doesn't stick. Repeat with the Cognac. Add the wine and reduce to a thick, syrupy consistency.",
      "Add both stocks and the roasted bones and bring to the boil, then reduce the heat and simmer for 2 hours, continuously skimming. Pass through a fine chinois into a clean saucepan and reduce to a velvety consistency. Season to taste, transfer to a container and reserve until required.",
    ],
  },
  {
    slug: "madeira-duck-sauce",
    name: "Madeira duck sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "3 kg duck bones, chopped",
      "100 g butter",
      "200 g shallots, thinly sliced",
      "4 garlic cloves",
      "10 g white peppercorns",
      "750 g Madeira",
      "750 g port",
      "2 kg veal stock",
      "2 kg chicken stock",
      "1 sprig thyme",
      "1 bay leaf",
      "cherry vinegar, to taste",
      "spoonful of confit shallots",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil. Once hot, add the duck bones, season with salt and roast until golden.",
      "Melt the butter in a large saucepan over a medium heat, add the shallots and garlic and cook until browned. Add the roasted bones and peppercorns, then pour in the Madeira and reduce to a glaze. Add the port and reduce to a glaze too.",
      "Add both stocks and the aromatics and bring to the boil, then reduce the heat and simmer for 2 hours, continuously skimming. Pass through a fine chinois, then muslin, into a container. Before serving, season with cherry vinegar and the confit shallots.",
    ],
  },
  {
    slug: "mutton-sauce",
    name: "Mutton sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "250 g lamb fat",
      "3 kg mutton trim, diced",
      "250 g butter",
      "200 g carrots, thinly sliced",
      "200 g onions, thinly sliced",
      "200 g celery, thinly sliced",
      "50 g garlic cloves",
      "10 sprigs thyme",
      "50 g sprigs rosemary",
      "4 kg lamb stock",
      "1 kg veal stock, reduced",
      "1 g white peppercorns",
      "salt, to taste",
      "sherry vinegar, to taste",
      "§ Sauce infusion",
      "200 g mutton sauce (above)",
      "8 g mint",
      "2 g rosemary",
      "6 sprigs thyme",
    ],
    method: [
      "Melt the lamb fat in a large saucepan over a medium heat, then add the diced mutton trim and cook until browned all over. Remove, drain in a colander and set aside.",
      "Add the butter, vegetables and garlic, season with salt, and cook until browned, then add the herbs and return the mutton, scraping the bottom so the trim doesn't stick. Add both stocks and the peppercorns and bring to the boil, then reduce the heat and simmer for 2 hours, continuously skimming. Pass through a chinois into a container and season with sherry vinegar.",
      "For the sauce infusion, bring the sauce to the boil in a small saucepan over a medium heat. As soon as it boils, add the herbs and remove from the heat. Infuse for 20 minutes, then strain through a chinois.",
    ],
  },
  {
    slug: "lamb-sauce",
    name: "Lamb sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "150 g lamb fat",
      "1.5 kg lamb trim, diced",
      "150 g butter",
      "1 carrot, diced",
      "1 onion, diced",
      "1 celery stick, diced",
      "2 garlic cloves",
      "6 sprigs thyme",
      "35 g sprigs rosemary",
      "10 g coriander seeds",
      "1 g white peppercorns",
      "700 g lamb stock",
      "200 g veal stock",
      "sherry vinegar, to taste",
      "salt, to taste",
    ],
    method: [
      "Melt the lamb fat in a large saucepan over a medium heat, add the diced lamb trim and cook until browned all over. Remove and set aside. Add the butter, vegetables and garlic and cook until browned.",
      "Add the aromatics, except the rosemary, and return the lamb trim, scraping the bottom so nothing sticks. Add both stocks and bring to the boil, then reduce the heat and simmer for 2 hours, continuously skimming.",
      "Strain through a fine chinois into a container and season with salt and sherry vinegar. Add the rosemary and infuse for 10 minutes. Pass through a chinois into a container over ice.",
    ],
  },
  {
    slug: "venison-sauce",
    name: "Venison sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "200 g grapeseed oil, plus extra for roasting",
      "3 kg venison bones",
      "3 kg venison trim",
      "250 g butter",
      "1 white onion, chopped",
      "1 carrot, chopped",
      "2 celery sticks, chopped",
      "100 g garlic cloves",
      "4 sprigs thyme",
      "1 bay leaf",
      "1 × 750-ml bottle port",
      "1 × 750-ml bottle red wine",
      "2 kg chicken stock",
      "2 kg veal stock",
      "4 sprigs rosemary",
      "10 juniper berries",
      "60 g Cabernet Sauvignon vinegar",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil. Add the venison bones and cook until golden.",
      "Heat the grapeseed oil in a stock pot over a medium heat. Add the venison trim, lightly season and cook until browned all over. Remove, set aside and pour off any excess fat. Add the butter, vegetables and garlic, lightly season and cook until browned, then add the thyme and bay and return the trim, scraping the bottom so nothing sticks. Pour in the port and reduce completely. Add the wine and reduce to a syrupy consistency.",
      "Add both stocks and the roasted bones and bring to the boil, then reduce the heat and simmer for 2 hours, regularly skimming. Pass through a fine chinois, then muslin, into a clean pan over a medium heat and reduce to a velvety consistency. Remove from the heat, add the rosemary and juniper and infuse for 5 minutes. Pass through a chinois into a clean bowl over ice and season with the Cabernet Sauvignon vinegar. Leave to cool.",
    ],
  },
  {
    slug: "grouse-sauce",
    name: "Grouse sauce",
    category: "stocks-and-sauces",
    ingredients: [
      "grapeseed oil, for roasting",
      "1.5 kg grouse bones and legs, chopped",
      "1.5 kg duck bones, chopped",
      "100 g butter",
      "150 g shallots, thinly sliced",
      "3 garlic cloves",
      "10 g white peppercorns",
      "750 g Madeira",
      "750 g port",
      "2 kg veal stock",
      "2 kg chicken stock",
      "4 sprigs thyme",
      "1 bay leaf",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 180°C / 350°F (fan). Heat an oven tray with a dash of grapeseed oil. Add the grouse bones and legs and duck bones, lightly season and cook until browned all over.",
      "Heat the butter in a large saucepan over a medium heat, add the shallots and garlic, lightly season and cook until browned. Add the peppercorns, then pour in the Madeira and reduce by three quarters. Add the roasted bones and port and reduce to about 100 ml.",
      "Add both stocks and the aromatics and bring to the boil, then reduce the heat and simmer for 2 hours, continuously skimming. Pass through a fine chinois, then muslin, into a container over ice.",
    ],
  },
  {
    slug: "braisage",
    name: "Braisage",
    category: "stocks-and-sauces",
    ingredients: [
      "125 g butter",
      "100 g shallots, thinly sliced",
      "1 garlic clove, sliced",
      "5 sprigs thyme",
      "5 g fennel seeds",
      "5 g coriander seeds",
      "150 g button mushrooms, thinly sliced",
      "200 g dry white vermouth",
      "500 g chicken stock",
    ],
    method: [
      "Melt half the butter in a medium saucepan over a medium heat, add the shallots, garlic, thyme and spices and sweat without letting the shallots take on colour.",
      "Once softened, add the mushrooms and cook until the water has evaporated, then add the vermouth, chicken stock and the remaining butter. Stir and reduce by half, then pass through a fine chinois into a container over an ice bath.",
    ],
  },

  // ———————————————————————— BUTTERS, PURÉES & BASICS ————————————————————————
  {
    slug: "beurre-noisette",
    name: "Beurre noisette",
    category: "butters",
    ingredients: ["250 g unsalted butter, cut into 1-cm (½-inch) dice", "salt, to taste"],
    method: [
      "Place a medium saucepan over a high heat, add the diced butter and allow to brown until there is a nutty aroma — be careful not to let it burn. Quickly remove from the heat.",
      "Pass the beurre noisette through a fine chinois, season to taste and reserve.",
    ],
  },
  {
    slug: "parsley-butter",
    name: "Parsley butter",
    category: "butters",
    ingredients: [
      "grapeseed oil, for frying",
      "2 garlic cloves, finely chopped",
      "40 g shallots, finely chopped",
      "60 g button mushrooms, finely chopped",
      "200 g butter, diced, at room temperature",
      "20 g flat-leaf parsley, finely chopped",
      "20 g Parma ham, finely chopped",
      "10 g ground almonds",
      "salt and pepper, to taste",
    ],
    method: [
      "Heat the grapeseed oil in a medium saucepan over a medium heat, add the garlic, shallots and button mushrooms and sweat down until completely soft and without colour. Set aside to cool.",
      "Once cool, put the mixture into a mixing bowl with all the remaining ingredients and mix well. Season to taste, then chill and reserve.",
    ],
  },
  {
    slug: "confit-shallots",
    name: "Confit shallots",
    category: "butters",
    ingredients: ["250 g grapeseed oil", "500 g shallots, brunoised", "salt, to taste"],
    method: [
      "Heat a spoonful of the oil in a medium saucepan over a low heat, add the shallots and sweat without colour, seasoning with salt. Once softened, add the remaining oil to cover.",
      "Cover with a cartouche and cook over a low heat for 45 minutes to 1 hour, stirring regularly, until completely soft. Check the seasoning.",
    ],
  },
  {
    slug: "egg-wash",
    name: "Egg wash",
    category: "butters",
    ingredients: ["1 egg", "20 g whole milk", "10 g water"],
    method: ["Combine all the ingredients in a small bowl and whisk."],
  },
  {
    slug: "onion-puree",
    name: "Onion purée",
    category: "butters",
    ingredients: [
      "50 g butter",
      "500 g white onions, sliced",
      "3 sprigs thyme, wrapped in muslin cloth",
      "100 g whole milk",
      "salt, to taste",
    ],
    method: [
      "Melt the butter in a large saucepan over a low heat. Add the onions and thyme, season with salt, and sweat for 30 minutes, stirring frequently so the onions don't colour. Add the milk and cook until completely soft.",
      "Remove the thyme, blend on full power until smooth, season to taste, pass through a chinois into a container and reserve until required.",
    ],
  },
  {
    slug: "mushroom-puree",
    name: "Mushroom purée",
    category: "butters",
    ingredients: [
      "grapeseed oil, for frying",
      "120 g shallots, thinly sliced",
      "100 g butter",
      "1.2 kg portobello mushrooms, thinly sliced",
      "350 g shiitake mushrooms, thinly sliced",
      "2 garlic cloves, sliced",
      "4 sprigs thyme, wrapped in muslin cloth",
      "500 g double cream",
      "salt, to taste",
    ],
    method: [
      "Heat the oil in a large saucepan over a medium heat, add the shallots and sweat down without colour. Add the butter and, when it foams, add the portobello and shiitake mushrooms, season, and cook until soft and lightly browned.",
      "Add the garlic, thyme and cream and bring to the boil, then reduce the heat and simmer until the mushrooms are tender. Check the seasoning, strain and reserve the liquid.",
      "Remove the thyme, blend the mushrooms on full speed, adding as much reserved liquid as needed for a smooth purée. Pass through a chinois into a container and season to taste. Reserve until required.",
    ],
  },
  {
    slug: "smoked-chestnuts",
    name: "Smoked chestnuts",
    category: "butters",
    ingredients: ["500 g vacuum-packed chestnuts", "apple wood chips, for smoking"],
    method: [
      "Place the chestnuts in a perforated tray and spread out in an even layer. Place the smoking chips in another tray and set them on fire with a blowtorch.",
      "Place the perforated tray on top and cover tightly with foil. Let it smoke for 1 hour, then remove and reserve until required.",
    ],
  },
  {
    slug: "lobster-butter",
    name: "Lobster butter",
    category: "butters",
    ingredients: [
      "grapeseed oil, for frying",
      "500 g lobster shells, crushed",
      "100 g carrots, diced",
      "100 g onions, diced",
      "100 g celery, diced",
      "300 g butter, cut into 2-cm (¾-inch) dice",
      "4 sprigs thyme",
      "2 garlic cloves, sliced",
      "20 g tomato purée (paste)",
    ],
    method: [
      "Heat the oil in a large saucepan over a high heat, add the crushed lobster shells and lightly brown all over, then add the diced vegetables and cook until light in colour.",
      "Add the butter, thyme and garlic and allow the butter to foam and take on a light colour. Add the tomato purée and cook for another 2 minutes, then reduce the heat and simmer for 30 minutes. Remove from the heat and infuse for 1 hour.",
      "Pass through a fine chinois lined with muslin. Discard the shells. Chill and reserve until required.",
    ],
  },
  {
    slug: "tomato-fondue",
    name: "Tomato fondue",
    category: "butters",
    ingredients: [
      "10 large San Marzano tomatoes",
      "50 g grapeseed oil",
      "100 g shallots, brunoised",
      "4 sprigs thyme",
      "2 garlic cloves, crushed and wrapped in muslin cloth",
      "50 g tomato purée (paste)",
      "salt, to taste",
      "caster sugar, to taste",
      "Barolo vinegar, to taste",
      "extra virgin olive oil, to taste",
    ],
    method: [
      "Peel and de-seed the tomatoes and reserve the juice. Finely dice the tomato petals.",
      "Heat the oil in a large saucepan over a medium heat, add the shallots, lightly season with salt, and sweat down without colour. Add the diced tomatoes, lightly season with salt and sugar, then add the thyme and garlic and cook out any remaining juices. Add the tomato purée and stir frequently so the tomatoes don't colour.",
      "Add the reserved tomato juice, reduce the heat and cover with a cartouche. Cook slowly for about 1 hour, until all the juice has been absorbed and the mixture is rich and thick. Remove from the heat and finish by seasoning with salt, sugar, vinegar and olive oil to taste.",
    ],
  },

  // —————————————————————————————— BRINES & PICKLES ——————————————————————————————
  {
    slug: "10-percent-herb-brine",
    name: "10% herb brine",
    category: "brines",
    ingredients: [
      "1.6 kg water",
      "160 g salt",
      "16 g rosemary",
      "10 g thyme",
      "1.6 g bay leaves",
      "10 g garlic cloves",
      "3 g black peppercorns",
    ],
    method: [
      "Combine the water and salt in a large saucepan and bring to the boil. Once the salt has dissolved, remove from the heat, set aside and cool to 40°C / 100°F, then add the herbs and aromatics.",
      "When completely cool, pass through a chinois and reserve in the fridge until required.",
    ],
  },
  {
    slug: "8-percent-herb-brine",
    name: "8% herb brine",
    category: "brines",
    ingredients: [
      "1 kg water",
      "75 g salt",
      "5 g pink salt",
      "20 g juniper berries",
      "10 g Tasmanian black peppercorns",
      "15 g coriander seeds",
      "10 g sprigs rosemary",
      "20 g sprigs thyme",
      "4 g bay leaves",
    ],
    method: [
      "Combine the water and both salts in a large saucepan and bring to the boil. Once dissolved, remove from the heat, set aside and cool to 40°C / 100°F.",
      "Lightly warm the spices in a pan to release their aroma, then add to the water along with the herbs. When the brine is completely cool, pass through a chinois and reserve in the fridge until required.",
    ],
  },
  {
    slug: "15-percent-herb-brine",
    name: "15% herb brine",
    category: "brines",
    ingredients: [
      "1 kg water",
      "150 g salt",
      "8 g sprigs rosemary",
      "8 g sprigs thyme",
      "1 g bay leaves",
      "8 g garlic cloves",
      "3 g black peppercorns",
    ],
    method: [
      "Combine the water and salt in a large saucepan and bring to the boil. Once the salt has dissolved, remove from the heat, set aside and cool to 40°C / 100°F, then add the herbs and aromatics.",
      "When completely cool, pass through a chinois and reserve in the fridge until required.",
    ],
  },
  {
    slug: "pickle-liquor",
    name: "Pickle liquor",
    category: "brines",
    ingredients: [
      "500 g water",
      "400 g Chardonnay vinegar",
      "10 g fennel seeds",
      "10 g coriander seeds",
      "4 g black peppercorns",
      "4 medium shallots, sliced",
      "15 g salt",
      "150 g caster sugar",
    ],
    method: [
      "Combine all the ingredients in a saucepan over a medium heat and bring to the boil to dissolve the salt and sugar.",
      "Set aside to cool, then pass through a fine chinois and reserve until required.",
    ],
  },
  {
    slug: "pickled-buddhas-hand",
    name: "Pickled Buddha's hand",
    category: "brines",
    ingredients: [
      "1 Buddha's hand",
      "500 g water",
      "400 g Chardonnay vinegar",
      "10 g salt",
      "150 g caster sugar",
    ],
    method: [
      "Cut the Buddha's hand lengthways into eight pieces and remove the pith. Cut into slices 2 mm (1/16 inch) thick and place in a container.",
      "Combine the water, vinegar, salt and sugar in a saucepan over a medium heat and bring to the boil. Continue to boil until the salt and sugar have dissolved, then pour over the sliced Buddha's hand and leave to cool. Place in the fridge until required.",
    ],
  },
  {
    slug: "pickled-ginger",
    name: "Pickled ginger",
    category: "brines",
    ingredients: [
      "250 g water",
      "250 g Chardonnay vinegar",
      "20 g salt",
      "125 g caster sugar",
      "3 g fennel seeds",
      "3 g white peppercorns",
      "3 g coriander seeds",
      "250 g peeled ginger, brunoised",
    ],
    method: [
      "Combine the water, vinegar, salt and sugar in a saucepan over a medium heat and bring to the boil. Continue to boil until the salt and sugar have completely dissolved.",
      "Add the spices and ginger, then remove from the heat. Set aside to cool, then place in the fridge until required.",
    ],
  },

  // ————————————————————————————————— OILS & GELS —————————————————————————————————
  {
    slug: "lovage-oil",
    name: "Lovage oil",
    category: "oils-and-gels",
    ingredients: ["500 g picked lovage leaves", "300 g grapeseed oil", "5 g salt", "5 g caster sugar"],
    method: [
      "Wash the lovage leaves, then drain in a salad spinner to remove excess water. Bring a medium saucepan of water to the boil and blanch the leaves for 10 seconds. Immediately refresh in ice water and squeeze dry.",
      "Transfer to a blender with the oil, salt and sugar and blend for 10 minutes until the mixture resembles a split purée. Pass through a fine chinois into a bowl over an ice bath, then pour into a sous vide bag, seal and hang at an angle in the fridge for 24 hours to let the water and oil separate.",
      "Once the water has drained to the bottom corner of the bag, cut a small hole to let it slowly escape, leaving only the oil. Reserve in the fridge in a squeeze bottle until required.",
    ],
  },
  {
    slug: "mint-oil",
    name: "Mint oil",
    category: "oils-and-gels",
    ingredients: ["250 g picked mint leaves", "400 g grapeseed oil", "2 g salt", "2 g caster sugar"],
    method: [
      "Wash the mint leaves, then drain in a salad spinner to remove excess water. Bring a medium saucepan of water to the boil and blanch the leaves for 20 seconds. Immediately refresh in ice water and squeeze dry.",
      "Transfer to a blender with the oil, salt and sugar and blend for 5 minutes until the mixture resembles a purée. Pass through a fine chinois into a bowl over an ice bath, then pour into a sous vide bag, seal and hang at an angle in the fridge for 24 hours to let the water and oil separate.",
      "Once the water has drained to the bottom corner of the bag, cut a small hole to let it slowly escape, leaving only the oil. Reserve in the fridge in a squeeze bottle until required.",
    ],
  },
  {
    slug: "oyster-leaf-oil",
    name: "Oyster leaf oil",
    category: "oils-and-gels",
    ingredients: [
      "200 g oyster leaves",
      "50 g borage leaves",
      "200 g grapeseed oil",
      "4 g caster sugar",
      "4 g salt",
    ],
    method: [
      "Place all the ingredients into a blender and blend for 5 minutes until the mix resembles a purée. Pass through a fine chinois into a bowl over an ice bath, then transfer to a sous vide bag and hang at an angle in the fridge for 24 hours to let the water and oil separate.",
      "Once the water has drained to the bottom corner of the bag, cut a small hole to let it slowly escape, leaving only the oil. Reserve in the fridge in a squeeze bottle until required.",
    ],
  },
  {
    slug: "woodruff-oil",
    name: "Woodruff oil",
    category: "oils-and-gels",
    ingredients: ["200 g woodruff leaves", "300 g grapeseed oil"],
    method: [
      "Wash the woodruff leaves, then drain in a salad spinner to remove excess water. Heat the oil in a saucepan to 60°C / 140°F.",
      "Place the leaves in a blender and blend, then slowly add the oil and blend for another 5 minutes. Transfer to a container and infuse for 24 hours. Strain through muslin, transfer to a sous vide bag and seal. Hang at an angle in the fridge for 24 hours to let the water and oil separate.",
      "Once the water has drained to the bottom corner of the bag, cut a small hole to let it slowly escape, leaving only the oil. Reserve in the fridge in a squeeze bottle until required.",
    ],
  },
  {
    slug: "black-truffle-puree",
    name: "Black truffle purée",
    category: "oils-and-gels",
    ingredients: [
      "250 g black truffle, finely chopped",
      "10 g truffle juice",
      "20 g black truffle oil",
      "balsamic noir vinegar, to taste",
      "Barolo vinegar, to taste",
      "salt, to taste",
    ],
    method: [
      "Place the black truffle and truffle juice in a mortar and crush with a pestle to form a paste, then add the truffle oil in a steady stream while mixing continuously.",
      "Season to taste using both vinegars and salt. Store in a container in the fridge.",
    ],
  },
  {
    slug: "mayonnaise",
    name: "Mayonnaise",
    category: "oils-and-gels",
    ingredients: [
      "200 g egg yolks",
      "2 cooked egg yolks (cooked for 12 minutes)",
      "50 g Dijon mustard",
      "20 g white wine vinegar",
      "1 kg grapeseed oil",
      "lemon juice, to taste",
      "salt, to taste",
    ],
    method: [
      "Put both the raw and cooked egg yolks into the bowl of a stand mixer fitted with the whisk attachment. Add the mustard and vinegar and whisk until smooth.",
      "Gradually add the oil in a steady stream, whisking continuously, until emulsified. Season to taste with lemon juice and salt.",
    ],
  },
  {
    slug: "nectarine-and-honey-gel",
    name: "Nectarine and honey gel",
    category: "oils-and-gels",
    ingredients: [
      "270 g verjus",
      "500 g honey",
      "300 g white wine",
      "600 g nectarine flesh",
      "12 g Gellan F",
    ],
    method: [
      "Combine all the ingredients except the Gellan F in a temperature-controlled blender and bring to 90°C / 200°F on a medium speed. Once it reaches temperature, add the Gellan F and blend on medium speed for 2½ minutes, then strain through a chinois into a container and leave to set in the fridge.",
      "Once fully set, break up the gel, blend until smooth, then pour into a deep, square container and compress in a sous vide machine until it becomes clear. Place in a squeeze bottle in the fridge until required.",
    ],
  },
  {
    slug: "pickle-gel",
    name: "Pickle gel",
    category: "oils-and-gels",
    ingredients: [
      "550 g pickled cucumber brine",
      "5 g salt",
      "12 g Gellan F",
      "90 g cornichons, brunoised",
    ],
    method: [
      "Put the pickled cucumber brine and salt into a temperature-controlled blender and bring to 90°C / 200°F on a medium speed. Once it reaches temperature, add the Gellan F and blend on medium speed for 2 minutes, then for another 30 seconds on full speed. Pour into a container and chill over an ice bath, then blend again for 4 minutes, scraping down the sides, until smooth.",
      "Transfer to a shallow container, place in a sous vide machine on programme 1 and close the lid. Let the gel rise to the top, then press stop; repeat twice more, or until clear. Pass through a fine chinois and mix in the brunoised cornichons.",
      "Place into a piping bag fitted with a 5-mm (¼-inch) nozzle and refrigerate until required.",
    ],
  },

  // ————————————————————————————————— MOUSSE —————————————————————————————————
  {
    slug: "chicken-mousse",
    name: "Chicken mousse",
    category: "mousse",
    ingredients: ["1 kg chicken breast", "40 g salt", "400 g double cream", "salt, to taste"],
    method: [
      "Place an empty blender jug into the freezer. Once chilled, add the chicken breast and blend on full speed for 30 seconds, then stop and scrape down. Repeat once more, scrape down again, add the salt and blend for another 30 seconds until smooth.",
      "Pass through a fine tamis into a bowl over ice, then beat with a spatula. Gradually add the cream, fully incorporating each addition before adding more, then season to taste. Reserve in a container in the fridge.",
    ],
  },

  // ————————————————————————————————— PASTRY —————————————————————————————————
  {
    slug: "clementine-puree",
    name: "Clementine purée",
    category: "pastry",
    ingredients: [
      "800 g clementines",
      "100 g caster sugar",
      "9 g pectin",
      "100 g clementine juice",
      "salt, to taste",
      "icing sugar, to taste",
    ],
    method: [
      "Blanch the whole clementines in a medium saucepan of boiling water three times, refreshing the water each time. Cut into quarters and transfer to a blender with the sugar, pectin and clementine juice. Blend on full speed until smooth.",
      "Season to taste with salt and icing sugar, then pass through a fine chinois and transfer to a piping bag fitted with a 5-mm (¼-inch) nozzle. Chill and reserve until required.",
    ],
  },
  {
    slug: "elderflower-cordial",
    name: "Elderflower cordial",
    category: "pastry",
    ingredients: [
      "1 kg water",
      "750 g caster sugar",
      "20 elderflower heads (washed, green stems removed)",
      "zest of 2 lemons",
      "10 g citric acid",
    ],
    method: [
      "Combine the water and sugar in a medium saucepan and bring to the boil. Put the elderflower heads and lemon zest into a heatproof bowl, then pour over the boiling syrup. Leave to steep for 12 hours in a cool place.",
      "Strain through muslin and discard the elderflower heads and zest. Add the citric acid. Store in the fridge.",
    ],
  },
  {
    slug: "gelatine-mass",
    name: "Gelatine mass",
    category: "pastry",
    ingredients: ["100 g water", "24 g gelatine powder"],
    method: ["Combine the water and gelatine in a bowl, whisk together and reserve in the fridge for 24 hours."],
  },
  {
    slug: "honey-crisps",
    name: "Honey crisps",
    category: "pastry",
    ingredients: [
      "100 g isomalt",
      "100 g liquid glucose",
      "25 g honey powder",
      "gold powder, for brushing",
    ],
    method: [
      "Combine the isomalt and glucose in a small saucepan over a high heat and heat to 158°C / 316°F. Pour onto a silicone mat and allow to cool.",
      "Preheat the oven to 160°C / 325°F (no fan). Blend the cooled mixture with the honey powder to a fine powder. Place a 5 × 8-cm (2 × 3-inch) rectangle stencil 1 mm thick onto a silicone mat and dust the powder over it through a fine chinois. Remove the stencil and bake for 4 minutes, then rest for 30 seconds.",
      "Once rested, peel the sugar from the mat, take each side and pull in opposite directions then back in to create a ruffled effect. Set on a tray, then brush with edible gold powder and reserve in an airtight container.",
    ],
  },
  {
    slug: "stock-syrup",
    name: "Stock syrup",
    category: "pastry",
    ingredients: ["225 g caster sugar", "25 g liquid glucose", "200 g water"],
    method: [
      "Combine all the ingredients in a saucepan over a medium heat and bring to the boil. Stir until the sugar has completely dissolved, then pour into a container and allow to cool.",
    ],
  },
  {
    slug: "hazelnut-praline",
    name: "Hazelnut praline",
    category: "pastry",
    ingredients: [
      "350 g hazelnuts, blanched",
      "100 g caster sugar",
      "75 g water",
      "50 g hazelnut oil",
      "salt, to taste",
    ],
    method: [
      "Preheat the oven to 160°C / 320°F (no fan). Spread the hazelnuts on a baking tray and roast for 15 minutes, tossing every 5 minutes, until golden.",
      "Put the sugar, water and salt into a medium saucepan over a high heat and heat to 155°C / 310°F to create a caramel. Add the toasted hazelnuts, then remove from the heat and transfer the nuts and caramel onto a tray to cool to room temperature.",
      "Blend the caramelized hazelnuts with the oil to a smooth paste, then season to taste.",
    ],
  },

  // ————————————————————————————————— BAKERY —————————————————————————————————
  {
    slug: "mature-rye-starter",
    name: "Mature rye starter",
    category: "bakery",
    ingredients: [
      "§ Day 1",
      "100 g whole rye flour",
      "100 g water, at room temperature",
      "§ Day 3 — to refresh",
      "200 g mix from above",
      "100 g whole rye flour",
      "100 g water, at room temperature",
      "§ Day 4 — to refresh",
      "200 g mix from above",
      "100 g whole rye flour",
      "100 g water, at room temperature",
    ],
    method: [
      "Day 1: Combine all the ingredients in a mixing bowl and leave in a warm place to ferment for 48 hours.",
      "Day 3: Combine all the ingredients in a mixing bowl and leave in a warm place to ferment for 24 hours.",
      "Day 4: Combine all the ingredients in a mixing bowl, cover with cling film and leave the dough at room temperature for 1–3 hours. Place in the fridge for 12 hours.",
      "Eat, sleep and repeat for a few years to give you a mature starter.",
    ],
  },
  {
    slug: "mature-white-starter",
    name: "Mature white starter",
    category: "bakery",
    ingredients: [
      "§ Day 1",
      "150 g strong white flour",
      "150 g water, at room temperature",
      "15 g honey",
      "§ Day 3 — to refresh",
      "150 g mix from above",
      "150 g strong white flour",
      "150 g water, at room temperature",
      "§ Day 4 — to refresh",
      "150 g mix from above",
      "150 g strong white flour",
      "150 g water, at room temperature",
      "§ Day 5 — to refresh",
      "200 g mix from above",
      "400 g strong white flour",
      "180 g water, at room temperature",
    ],
    method: [
      "Day 1: Combine all the ingredients in a mixing bowl and leave in a warm place to ferment for 48 hours.",
      "Day 3: Combine all the ingredients in a mixing bowl and leave in a warm place to ferment for 24 hours.",
      "Day 4: Combine all the ingredients in a mixing bowl and leave in a warm place to ferment for 24 hours.",
      "Day 5: Combine all the ingredients in a mixing bowl, cover with cling film and leave the dough at room temperature for 1–3 hours. Place in the fridge for 12 hours.",
      "Eat, sleep and repeat for a few years to give you a mature starter.",
    ],
  },
];

export function coreRecipesByCategory(id: CoreCategoryId) {
  return coreRecipes.filter((recipe) => recipe.category === id);
}
