import type { ImportedCookbookRecipe } from "@/components/imported-cookbook-guide";

type BlendSeed = {
  title: string;
  region: string;
  page: number;
  ingredients: string[];
  method: string;
};

const blend = ({ title, region, page, ingredients, method }: BlendSeed): ImportedCookbookRecipe => ({
  id: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  title,
  subtitle: `Local spice blend · ${region}`,
  category: `Regional blends · ${region}`,
  sourcePages: [page],
  ingredientGroups: [{ heading: "Ingredients", lines: ingredients }],
  methodGroups: [{ heading: "Method", steps: [method] }],
  searchText: `${title} ${region} ${ingredients.join(" ")} ${method}`,
});

export const scienceOfSpiceRegionalBlends: ImportedCookbookRecipe[] = [
  blend({ title: "Za’atar", region: "Middle East", page: 22, ingredients: ["2 tbsp cumin seeds", "1 tsp sea salt", "2 tbsp sesame seeds", "2 tbsp dried oregano", "2 tbsp sumac"], method: "Toast the cumin and grind it with the salt. Toast the sesame seeds, then combine with the oregano and sumac." }),
  blend({ title: "Turkish baharat", region: "Middle East", page: 23, ingredients: ["2 tbsp black peppercorns", "2 tbsp cumin seeds", "2 tbsp coriander seeds", "1 tsp cloves", "½ tbsp cardamom seeds", "1 tbsp ground nutmeg", "Pinch of ground cinnamon", "1 tbsp dried mint"], method: "Grind the whole spices, then mix in the nutmeg, cinnamon, and mint." }),
  blend({ title: "Zhug", region: "Middle East", page: 24, ingredients: ["1 tsp cardamom seeds", "1 tsp coriander seeds", "1 tsp cumin seeds", "2 green chillies, chopped", "2 garlic cloves, chopped", "1 large bunch coriander", "Olive oil and salt"], method: "Grind the spices, then blend with the chillies, garlic, coriander, oil, and salt to a coarse green paste." }),
  blend({ title: "Taklia", region: "Middle East", page: 25, ingredients: ["Garlic", "Coriander", "Cumin", "Ground cinnamon", "Black pepper", "Allspice", "Cloves", "Oil or butter"], method: "Fry the garlic and spices in oil or butter until fragrant; use the hot seasoning to finish soups and stews." }),
  blend({ title: "Arabic baharat", region: "Middle East", page: 26, ingredients: ["1 tbsp black peppercorns", "1 tbsp allspice", "1 tsp cloves", "1 tsp coriander seeds", "1 tsp cumin seeds", "1 tbsp ground cinnamon", "1 tsp grated nutmeg"], method: "Grind the whole spices, then combine with the cinnamon, cumin, and nutmeg." }),
  blend({ title: "Advieh", region: "Middle East", page: 27, ingredients: ["2 tbsp dried rose petals", "2 tbsp cardamom seeds", "1 tbsp cumin seeds", "1 tbsp cinnamon", "1 tbsp coriander seeds", "1 tsp nutmeg"], method: "Grind the whole spices and rose petals finely, then mix with the ground spices." }),
  blend({ title: "Dukkah", region: "Middle East", page: 28, ingredients: ["150g hazelnuts", "150g whole almonds", "1 tbsp coriander seeds", "1 tbsp cumin seeds", "3 tbsp sesame seeds", "Pinch of salt"], method: "Roast the nuts, dry-fry the seeds, then pulse everything with salt to a coarse, crunchy mixture." }),
  blend({ title: "Hawaij", region: "Middle East", page: 29, ingredients: ["Black pepper", "Cumin", "Cardamom", "Turmeric", "Coriander", "Cloves"], method: "Toast and grind the whole spices, then blend with the ground spices for a curry-like Yemeni seasoning." }),
  blend({ title: "Niter kibbeh", region: "Africa", page: 32, ingredients: ["500g unsalted butter", "1 medium onion, finely chopped", "2 garlic cloves", "1 tbsp ginger", "1 tsp fenugreek", "1 tsp ground cumin", "1 tsp korarima or cardamom", "½ tsp turmeric", "1 tsp oregano", "6 basil leaves", "4 sage leaves"], method: "Melt the butter over low heat with the aromatics and spices for about 20 minutes, then strain." }),
  blend({ title: "Harissa", region: "Africa", page: 33, ingredients: ["100g dried red chillies", "Garlic", "Coriander seeds", "Caraway seeds", "Cumin seeds", "Olive oil", "Salt"], method: "Soak the chillies, toast and grind the spices, then blend everything to a smooth paste with olive oil." }),
  blend({ title: "Pilau masala", region: "Africa", page: 34, ingredients: ["½ tsp cumin seeds", "½ tsp whole black peppercorns", "½ tsp cloves", "¼ tsp cardamom", "¼ tsp cinnamon"], method: "Dry-fry the whole spices until fragrant, cool, and grind finely." }),
  blend({ title: "Mbongo mix", region: "Africa", page: 35, ingredients: ["4 tsp ground mbongo or black cardamom", "1 tsp bobimbi, wild garlic, or garlic chives", "30 njangsa seeds or a handful of peanuts", "2 calabash nutmeg or 1 tsp nutmeg", "1 tsp grains of paradise", "4 garlic cloves", "1 onion", "4 tbsp water"], method: "Blend all the ingredients with the water to make the paste for mbongo tchobi." }),
  blend({ title: "Yaji", region: "Africa", page: 36, ingredients: ["10 strands grains of Selim", "1 tbsp whole Ashanti pepper", "5 tbsp crushed kuli-kuli or peanut puffs", "5 tbsp ginger powder", "2 tbsp cayenne flakes", "1 stock cube", "½ tsp salt", "Black pepper"], method: "Grind the whole spices, sieve out tough fibres, then mix with the remaining ingredients." }),
  blend({ title: "Durban curry masala", region: "Africa", page: 37, ingredients: ["2 tsp coriander seeds", "2 tsp cumin seeds", "1 tsp cardamom seeds", "½ tsp fenugreek seeds", "Cinnamon", "Cloves", "Cayenne pepper", "Ground ginger"], method: "Toast and grind the whole spices, then combine with the cayenne and ginger." }),
  blend({ title: "Garam masala", region: "South Asia", page: 40, ingredients: ["25g black cardamom seeds", "25g cassia bark", "25g black peppercorns", "10g black cumin", "2 mace blades", "10g cloves", "⅛ nutmeg"], method: "Grind the spices together and pass through a fine sieve." }),
  blend({ title: "Timur ko chhop", region: "South Asia", page: 41, ingredients: ["Timur (Sichuan pepper)", "Dried red chillies", "Salt", "Garlic", "Coriander"], method: "Toast and grind the timur and chillies, then mix with salt and the remaining aromatics for a fiery seasoning." }),
  blend({ title: "Chaat masala", region: "South Asia", page: 42, ingredients: ["2 tbsp cumin seeds", "1 tsp coriander seeds", "1 tbsp black peppercorns", "3 tbsp amchoor", "1 tsp ground ginger", "½ tsp asafoetida", "1 tbsp kala namak", "1 tsp salt"], method: "Toast the whole spices, cool, then grind and mix with the remaining ingredients." }),
  blend({ title: "Panch phoran", region: "South Asia", page: 43, ingredients: ["2 tsp cumin seeds", "2 tsp brown mustard seeds", "2 tsp fennel seeds", "2 tsp fenugreek seeds", "2 tsp nigella seeds"], method: "Mix the five whole spices; use them unground to temper dhal and vegetable dishes." }),
  blend({ title: "Vindaloo paste", region: "South Asia", page: 44, ingredients: ["1½ tsp cumin seeds", "15–20 dried Kashmiri chillies", "1 tsp black peppercorns", "2 tsp black mustard seeds", "1 tsp fenugreek seeds", "6 cloves", "1 tsp cardamom seeds", "5cm cassia", "½ star anise", "6 tbsp cider or palm vinegar", "1 tsp salt", "2 tsp jaggery or date sugar"], method: "Toast and grind the spices, then mix with vinegar, salt, and sugar to make a stiff paste." }),
  blend({ title: "Gunpowder", region: "South Asia", page: 45, ingredients: ["25g chana dhal", "25g urad dhal", "25g dried coconut", "1 tbsp black sesame seeds", "2 tbsp curry leaves", "6–8 dried red chillies", "1 tbsp tamarind pulp", "¼ tsp asafoetida", "2 tsp jaggery"], method: "Toast the dhal, coconut, sesame, curry leaves, and chillies separately; cool and grind with the remaining ingredients." }),
  blend({ title: "Burmese garam masala", region: "Southeast Asia", page: 48, ingredients: ["1 tsp coriander seeds", "1 tsp black peppercorns", "1 tsp cumin seeds", "2 bay leaves", "1 tsp cardamom seeds", "1 tsp cloves", "2.5cm cinnamon stick", "2 star anise"], method: "Toast the spices, cool completely, then grind finely." }),
  blend({ title: "Khao kua", region: "Southeast Asia", page: 49, ingredients: ["5 tbsp glutinous rice", "Kaffir lime leaves", "Lemongrass", "Galangal"], method: "Toast the rice until deep golden, then grind with the dried aromatics to a coarse powder." }),
  blend({ title: "Nuoc cham", region: "Southeast Asia", page: 50, ingredients: ["2 bird’s-eye chillies", "1 garlic clove", "2 tsp palm sugar", "Juice of ½ lime", "2 tbsp fish sauce", "2 tbsp water"], method: "Pound the chillies, garlic, and sugar; stir in the lime juice, water, and fish sauce." }),
  blend({ title: "Malaysian fish curry paste", region: "Southeast Asia", page: 51, ingredients: ["2 tsp coriander seeds", "1 tsp cumin seeds", "½ tsp fennel seeds", "½ tsp black peppercorns", "4 dried chillies", "½ tsp turmeric", "Thumb-sized galangal", "3 garlic cloves", "50g shallots"], method: "Toast the dry spices, then blend with the chillies and fresh aromatics to a smooth paste." }),
  blend({ title: "Bumbu", region: "Southeast Asia", page: 52, ingredients: ["1 tsp coriander seeds", "3 cloves", "½ tsp white pepper", "Pinch of nutmeg", "1.5cm galangal", "2.5cm turmeric", "6 shallots", "3 garlic cloves", "2 red chillies", "1 tsp shrimp paste", "1 tbsp oil"], method: "Blend the ingredients to a smooth paste, then fry in oil until fragrant before using." }),
  blend({ title: "Adobo marinade", region: "Southeast Asia", page: 53, ingredients: ["100ml coconut vinegar", "50ml soy sauce", "3 garlic cloves", "1 tsp black pepper", "2 bay leaves"], method: "Simmer the ingredients briefly, then cool before marinating chicken or pork." }),
  blend({ title: "Yangnyeomjang", region: "East Asia", page: 56, ingredients: ["2 tsp white sesame seeds", "3 tbsp soy sauce", "1 tbsp toasted sesame oil", "½ tsp rice vinegar", "2 tsp gochugaru", "½ tsp sugar or honey", "1 garlic clove", "1 spring onion"], method: "Toast the sesame seeds and mix with the remaining ingredients; refrigerate for up to a week." }),
  blend({ title: "Shichimi-togarashi", region: "East Asia", page: 57, ingredients: ["Dried red chilli", "Sichuan pepper", "Sesame seeds", "Dried orange peel", "Ginger", "Nori", "Poppy seeds"], method: "Toast the seeds and grind with the remaining dry ingredients to a fragrant table seasoning." }),
  blend({ title: "Shandong spice bag", region: "East Asia", page: 58, ingredients: ["10 cardamom pods", "2 star anise", "½ tbsp Sichuan peppercorns", "½ tbsp cloves", "½ tbsp cumin seeds", "7.5cm cinnamon stick", "10–12cm liquorice root", "Dried orange or tangerine peel"], method: "Tie the spices in muslin or a spice bag and use to flavour master stock." }),
  blend({ title: "Nanjing spice bag", region: "East Asia", page: 59, ingredients: ["6 cloves", "4 star anise", "1 tsp crushed white pepper", "6 bay leaves", "Dried tangerine peel", "1 tsp liquorice root", "1 tsp salt"], method: "Tie in a spice bag and add to poaching liquid with fresh ginger and Shaoxing wine." }),
  blend({ title: "Five-spice powder", region: "East Asia", page: 60, ingredients: ["2 star anise", "1 tsp fennel seeds", "1 tsp cloves", "5cm cinnamon stick", "1 tbsp Sichuan peppercorns"], method: "Grind the spices and pass through a fine sieve." }),
  blend({ title: "Chilli black bean sauce", region: "East Asia", page: 61, ingredients: ["Fermented black beans", "Dried red chillies", "Garlic", "Ginger", "Sichuan pepper", "Oil", "Salt"], method: "Soak and chop the beans, then pound or blend with the aromatics and chillies into a robust paste." }),
  blend({ title: "Jamaican jerk rub", region: "Americas", page: 64, ingredients: ["2 tsp allspice", "1 tsp black peppercorns", "½ tsp cloves", "1 tsp chipotle or cayenne", "1 tsp paprika", "1 tsp nutmeg", "1 tsp ginger", "½ tsp cinnamon", "2 tsp onion powder", "2 tsp garlic powder", "1 tsp dried thyme", "2 tsp brown sugar", "2 tsp salt"], method: "Grind the whole spices and combine with the remaining ingredients." }),
  blend({ title: "Mole mix", region: "Americas", page: 65, ingredients: ["2 each dried ancho, pasilla, and mulato chillies", "3 tbsp cacao nibs", "1 tbsp sesame seeds", "2cm cinnamon stick", "¼ tsp cumin", "¼ tsp anise", "¼ tsp black pepper", "¼ tsp cloves", "¼ tsp thyme", "¼ tsp marjoram", "1 bay leaf"], method: "Toast the chillies, cacao, sesame, and whole spices, then grind with the herbs and bay leaf." }),
  blend({ title: "Chimichurri", region: "Americas", page: 66, ingredients: ["1 tsp chilli powder", "½ tsp dried chilli flakes", "½ tsp paprika", "2 garlic cloves", "1 onion", "4 tsp parsley or coriander", "1 tsp oregano", "3 tsp wine vinegar", "6 tbsp olive oil", "Salt and pepper"], method: "Finely chop the aromatics and herbs, then stir together with the spices, vinegar, oil, salt, and pepper." }),
  blend({ title: "Tucupí", region: "Americas", page: 67, ingredients: ["2kg cassava", "2 garlic cloves", "3–4 chillies", "1 tsp ground black pepper"], method: "Prepare only with properly processed cassava liquid: ferment and boil it thoroughly before seasoning with the garlic, chillies, and pepper." }),
  blend({ title: "Leche de tigre", region: "Americas", page: 68, ingredients: ["Ají limo, habanero, or other hot chilli", "Lime juice", "Garlic", "Fresh ginger", "Coriander", "Red onion", "White fish trim", "Salt"], method: "Blend the aromatics, fish trim, and lime juice briefly, strain, and use immediately to marinate ceviche." }),
  blend({ title: "BBQ rub", region: "Americas", page: 69, ingredients: ["1 tbsp ground cumin", "1 tbsp chilli powder", "1 tbsp black pepper", "1 tbsp onion powder", "1 tbsp garlic powder", "½ tbsp cayenne", "3 tbsp brown sugar", "2 tbsp smoked paprika", "2 tbsp salt"], method: "Mix all ingredients thoroughly and use as a dry rub for barbecued meat." }),
  blend({ title: "Mulling spice", region: "Europe", page: 72, ingredients: ["2 cinnamon sticks", "6 cloves", "6 allspice berries", "½ nutmeg", "2 bay leaves"], method: "Infuse the spices in gently warmed red wine or cider, then strain before serving." }),
  blend({ title: "Finnish gingerbread spice", region: "Europe", page: 73, ingredients: ["1 tbsp bitter orange powder", "2 tsp ground cloves", "2 tsp ground cinnamon", "2 tsp ground ginger", "1 tsp ground cardamom"], method: "Mix the ground spices thoroughly and store airtight for gingerbread baking." }),
  blend({ title: "Quatre épices", region: "Europe", page: 74, ingredients: ["1 tbsp white peppercorns", "1 tsp cloves", "1 tsp ground nutmeg", "1 tsp ground ginger"], method: "Grind the pepper and cloves, then mix with the nutmeg and ginger." }),
  blend({ title: "Paella mix", region: "Europe", page: 75, ingredients: ["2 pinches saffron", "3 tbsp pimentón", "2 tsp garlic powder", "2 tsp onion powder", "1 tsp cayenne", "1 tsp black pepper", "1 tsp dried oregano", "½ tsp dried parsley", "½ tsp cloves", "½ tsp cumin"], method: "Combine all ingredients, keeping the saffron lightly crushed, for a ready paella seasoning." }),
  blend({ title: "Arrabiata sauce", region: "Europe", page: 76, ingredients: ["1 tbsp hot red chilli flakes", "1 tsp dried oregano", "1 tsp garlic", "Black pepper", "Olive oil", "Tomatoes"], method: "Sizzle the chilli, oregano, garlic, and pepper in olive oil, then simmer with tomatoes for a quick sauce." }),
  blend({ title: "Khmeli-suneli", region: "Europe", page: 77, ingredients: ["Blue fenugreek", "Coriander", "Marigold petals", "Summer savoury", "Dill", "Mint", "Black pepper", "Chilli"], method: "Grind or finely mix the dried herbs and spices for a Georgian meat rub or stew seasoning." }),
];
